language: node_js

node_js:
  - "lts/argon"
  - "lts/boron"
  - "lts/carbon"
  - "node"

before_script:
  - mkdir -p test/keys
  - openssl genrsa -out test/keys/ssl.key 2048
  - openssl req -new -key test/keys/ssl.key -x509 -days 999 -out test/keys/ssl.cert
