language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "lts/argon"
  - "lts/boron"
  - "lts/carbon"
  - "node"

before_script:
  - mkdir -p test/keys
  - cp /etc/travis/ssl/ssl.key test/keys
  - cp /etc/travis/ssl/ssl.cert test/keys
